- README.md
- backend/src/main.rs
- frontend/.prettierrc
- frontend/package.json
- frontend/src/Errors.tsx
- frontend/src/FriendSelect.tsx
- frontend/src/Trump.tsx
- frontend/src/beep.ts
- frontend/src/index.tsx
- frontend/src/memoize.ts
- frontend/src/types.ts
- frontend/static/index.html
- frontend/tsconfig.json
- frontend/webpack.config.js
- frontend/yarn.lock
r? @rbtying 
Updated tsconfig to allow imports from node modules (React/ReactDOM) and local component files. I moved some code into separate files:
- Error, the simplest component I could find
- beep function
- Trump component, as well as changing ITrump into a disjoint union to prevent the impossible case
- FriendSelect
Added prettier, can be run with `yarn prettier --fix`
> Use modules, add prettier

- core/src/types.rs
- frontend/src/index.tsx
- frontend/static/rules.html
- order the trumps consistently
- separate points by suit
- note that the 2-2-2-3-3 play is a throw in the tractor section
- reorder suits diamonds->clubs->hearts->spades
> Clean up rules and make them easier to read

- frontend/package.json
- frontend/src/Card.tsx
- frontend/src/Credits.tsx
- frontend/src/GameMode.tsx
- frontend/src/LabeledPlay.tsx
- frontend/src/Trick.tsx
- frontend/src/index.tsx
- frontend/src/types.ts
- frontend/src/util/mapObject.ts
- frontend/yarn.lock
r? @rbtying 
- Added `classnames` package, which handles some of the common React classname manipulation patterns
- Moved more components/types into separate files
- Fully removed `e = React.createElement`; everything is on TSX now
> Extract more components

- README.md
- frontend/package.json
- frontend/src/FriendSelect.tsx
- frontend/src/GameMode.tsx
- frontend/src/SettingsButton.tsx
- frontend/src/Trick.tsx
- frontend/src/Trump.tsx
- frontend/src/index.tsx
- frontend/tsconfig.json
- frontend/tslint.json
- frontend/yarn.lock
r? @rbtying 
Added tslint with recommended configuration and enabled the `noUnusedLocals` option in tsconfig
> Add tslint

- core/src/game_state.rs
- core/src/interactive.rs
- frontend/src/index.tsx
- frontend/static/style.css
r? @danwang 
Add a reset button for when the game should be set back to the initialize state. Fixes #20
> Add reset button

- frontend/src/AppStateProvider.tsx
- frontend/src/index.tsx
Followup to #26. This takes two other pieces of local state and moves them to read/write from AppState, removing them from the global state
> Move name and room_name to AppState

- frontend/src/GameMode.tsx
- frontend/src/SettingsButton.tsx
- frontend/src/index.tsx
- frontend/static/index.html
- frontend/static/style.css
- Alternate Chinese and English names
- Align settings gear with text
- Click on room name to change the room name
- Separate out game-settings section and reorganize a bit
> Clean up landing page and game UI

- Cargo.lock
- backend/src/main.rs
- core/Cargo.toml
- core/src/game_state.rs
- core/src/interactive.rs
- frontend/src/Header.tsx
- frontend/src/SettingsPane.tsx
- frontend/src/index.tsx
- frontend/src/types.ts
- Allow users to set a "chat link" in the settings pane for other
players
- Allow users to set the kitty size
- Allow users to set the number of friends
- Wrap all game messages in BroadcastMessage for future refactoring
- Ensure that settings are retained across games and restarts
> Add a bunch of features

- frontend/src/Friends.tsx
- frontend/src/MovePlayerButton.tsx
- frontend/src/Players.tsx
- frontend/src/WebsocketProvider.tsx
- frontend/src/index.tsx
> Extract more components to separate files

- frontend/src/SettingsPane.tsx
- frontend/src/index.tsx
- frontend/src/state/Settings.ts
Fixes #42, though not optimally
> Add setting that allows you to reverse your cards (highest on left rather than highest on right)

- backend/src/main.rs
- core/src/game_state.rs
- core/src/interactive.rs
- frontend/src/Chat.tsx
- frontend/src/index.tsx
- frontend/src/websocketHandler.ts
Part 1 of the necessary infrastructure for #32
> Use structured broadcast messages in the game engine

- frontend/src/AutoPlayButton.tsx
- frontend/src/Play.tsx
- frontend/src/SettingsPane.tsx
- frontend/src/index.tsx
- frontend/src/state/Settings.ts
- frontend/src/util/usePrevious.ts
r? @rbtying 
Changes the "Play" button to an autoplay button.
- If it is your turn:
- Automatically submit the play if autoplay state is true
- Disabled when it's an invalid play (wrong number of cards)
- Enabled if you have the right number of cards, or first to play
- If it's not your turn:
- Can click "Autoplay"
- Changing selected cards unsets autoplay
Fixes #10
> Autoplay button

- core/src/trick.rs
> Sort cards when they are played in a trick.

- core/src/game_state.rs
- core/src/interactive.rs
- core/src/trick.rs
- frontend/src/LabeledPlay.tsx
- frontend/src/Play.tsx
- frontend/src/Points.tsx
- frontend/src/Trick.tsx
- frontend/src/index.tsx
- frontend/src/types.ts
- frontend/static/style.css
> Add basic throw support to the game

- README.md
- backend/src/main.rs
- frontend/custom_typings/json-loader.d.ts
- frontend/package.json
- frontend/src/cardInfo.ts
- frontend/src/generated/cards.json
- frontend/src/index.tsx
- frontend/static/index.html
- frontend/static/rules.html
- frontend/tslint.json
- frontend/yarn.lock
r? @rbtying 
Removes `cards.js` in favor generating a JSON file.
`yarn download-cards-json` downloads and puts it in `src/generated/cards.json`
I didn't write a test to check that they matched
> Export cards as checked in generated JSON

- frontend/src/EllipseLayout.tsx
r? @rbtying 
Adds a component that lays out children in a circle/ellipse, e.g.
> Add EllipseLayout

- frontend/src/Card.tsx
- frontend/src/FriendSelect.tsx
- frontend/src/Friends.tsx
- frontend/src/Points.tsx
- frontend/src/index.tsx
r? @rbtying 
- Replaces `CARD_LUT` with `lookupCard`
- Use InlineCard with FriendList
- Replace `window.CARD` with `preloadedCards`
> Remove global CARD_LUT

- frontend/src/Kicker.tsx
- frontend/src/LandlordSelector.tsx
- frontend/src/NumDecksSelector.tsx
- frontend/src/RankSelector.tsx
- frontend/src/index.tsx
r? @rbtying 
Moved NumDecksSelector and RankSelector. I changed their interfaces to be "controlled component" style, meaning they are only given the value/updater that they need. So these don't need to directly know about websocket or its message format
> Extract pre-game selectors into separate files

- backend/src/main.rs
- core/src/game_state.rs
- core/src/interactive.rs
- frontend/src/index.tsx
- frontend/src/types.ts
- Remove GameState::Done
- Remove Arc<Mutex<>> in InteractiveGame (caller already has a lock)
> Clean up unnecessary Rust code

- frontend/src/AppStateProvider.tsx
- frontend/src/Beeper.tsx
- frontend/src/Errors.tsx
- frontend/src/MovePlayerButton.tsx
- frontend/src/Play.tsx
- frontend/src/SettingsButton.tsx
- frontend/src/Timeout.tsx
- frontend/src/TimerProvider.tsx
- frontend/src/WebsocketProvider.tsx
- frontend/src/index.tsx
r? @rbtying 
Turns out there's a hook to avoid the lengthy renderprop variant of the `*Consumer`s.
> Use React.useContext hook

- frontend/src/Play.tsx
- frontend/src/Root.tsx
- frontend/src/SettingsPane.tsx
- frontend/src/Trick.tsx
- frontend/src/state/Settings.ts
- frontend/static/style.css
> Implement setting to show tricks in player order

- frontend/src/Draw.tsx
- frontend/src/Exchange.tsx
- frontend/src/Initialize.tsx
- frontend/src/Play.tsx
- frontend/src/Players.tsx
- frontend/static/style.css
> Implement toggle for observer/non-observer mode

- backend/src/main.rs
- core/src/game_state.rs
- core/src/interactive.rs
- frontend/src/BeepButton.tsx
- frontend/src/Draw.tsx
- frontend/src/Play.tsx
- frontend/src/websocketHandler.ts
> Implement functionality to beep the current player

- core/src/trick.rs
> Fix issue where tractor-throw evaluation was not correct

- frontend/src/RankSelector.tsx
- frontend/src/TimerProvider.tsx
- frontend/src/WebsocketProvider.tsx
- frontend/src/index.tsx
> Set a timeout after sending a message to determine if the socket is still alive

- frontend/src/Card.tsx
- frontend/src/Root.tsx
- frontend/src/SettingsPane.tsx
- frontend/src/state/Settings.ts
- frontend/static/style.css
This helps for people who aren't easily able to tell the cards apart.
> Add support for showing card labels on hover (and in settings)

- frontend/src/Initialize.tsx
> Fix typo in setting the number of friends

- core/src/game_state.rs
- core/src/interactive.rs
- core/src/message.rs
- frontend/src/Draw.tsx
> Enable the ability to take back bids

- core/src/game_state.rs
- frontend/src/websocketHandler.ts
> Set beep rate-limit to 1 per second and fix landlord->observer

- core/src/trick.rs
Previously, the trick-format decomposition didn't keep the requirement
for repeated <= 2 after another stage of decomposition. This made it so
that decomposing longer tractors would end up with no requirements
before passing through the n-tuple requirement case.
- Fixes #105
> Change trick decomp to do full decompositions

- core/src/game_state.rs
- core/src/hands.rs
- core/src/interactive.rs
- core/src/message.rs
- core/src/trick.rs
- frontend/src/Credits.tsx
- frontend/src/Draw.tsx
- frontend/src/Initialize.tsx
- frontend/src/types.ts
- frontend/static/style.css
Also, implement bidding using the player's current level when the winner of the
last round is unknown.
> Implement bidding from the kitty via revealing cards

- core/src/game_state.rs
- core/src/interactive.rs
- core/src/message.rs
- core/src/trick.rs
- frontend/src/Credits.tsx
- frontend/src/Initialize.tsx
- frontend/src/types.ts
Fixes bug reported on #112 
Fixes #36
> Evaluate throw on highest card

- core/src/game_state.rs
- frontend/src/Credits.tsx
- frontend/src/FriendSelect.tsx
I only tested with actual running cases for both trump and no trump, not sure if there are any integrated test cases required.
> #35, disallow picking trump cards as friend

- core/src/game_state.rs
- core/src/interactive.rs
- frontend/src/Credits.tsx
- frontend/src/Exchange.tsx
- frontend/src/FriendSelect.tsx
- frontend/src/Friends.tsx
- frontend/src/Play.tsx
- frontend/src/types.ts
I added changes for #125 in Credits.tsx in this commit as well
> #127, simplify friend selection description

- core/src/game_state.rs
- frontend/src/Credits.tsx
- frontend/src/Exchange.tsx
- frontend/src/FriendSelect.tsx
- frontend/src/Friends.tsx
- frontend/src/Initialize.tsx
- frontend/src/Play.tsx
- frontend/src/Trick.tsx
> Fix bug in defend-points, fix bug in prev-trick UI

- frontend/src/Players.tsx
- frontend/static/style.css
This makes macOS render better
> Set line-height to 1em in more places

- frontend/src/Card.tsx
- frontend/src/LabeledPlay.tsx
- frontend/static/style.css
> Ensure that failed-throw cards in SVG mode show up smaller

- core/src/bidding.rs
- core/src/game_state.rs
- core/src/interactive.rs
- core/src/lib.rs
- core/src/message.rs
- frontend/src/BidArea.tsx
- frontend/src/Credits.tsx
- frontend/src/Draw.tsx
- frontend/src/Exchange.tsx
- frontend/src/Initialize.tsx
- frontend/src/LandlordSelector.tsx
- frontend/src/Root.tsx
- frontend/src/types.ts
> Implement "stealing the kitty", and other cleanup

- frontend/src/Card.tsx
- frontend/static/index.html
- frontend/static/rules.html
- frontend/static/style.css
Also, allow the currently highlighted card to pop-up a bit
> Tighten the boundaries around cards

- core/src/game_state.rs
- frontend/package.json
- frontend/src/AppStateProvider.tsx
- frontend/src/ChatMessage.tsx
- frontend/src/Confetti.tsx
- frontend/src/Credits.tsx
- frontend/src/Root.tsx
- frontend/src/types.ts
- frontend/src/websocketHandler.ts
- frontend/webpack.config.js
- frontend/yarn.lock
> Add confetti/full screen notification on win

- backend/src/main.rs
- frontend/package.json
- frontend/static/index.html
- frontend/webpack.config.js
- frontend/yarn.lock
Hopefully gets around caching issues?
> Cache-bust by including the SHA in the filename

- core/src/game_state.rs
- frontend/src/Credits.tsx
- frontend/src/Exchange.tsx
> Allow beeps during the exchange phase

- frontend/shengji-wasm/src/lib.rs
- frontend/src/Initialize.tsx
> ensure that decksEffective > 0

- frontend/src/WebsocketProvider.tsx
> Handle browsers which don't support Blob.arrayBuffer()

- core/src/game_state.rs
- core/src/interactive.rs
- core/src/scoring.rs
- core/src/settings.rs
- frontend/shengji-wasm/src/lib.rs
- frontend/src/ChatMessage.tsx
- frontend/src/Credits.tsx
- frontend/src/ScoringSettings.tsx
- frontend/src/WasmContext.tsx
- frontend/src/WasmProvider.tsx
- frontend/src/types.ts
> Support more granular step sizes in scoring settings

- frontend/src/ScoringSettings.tsx
> Fix the scoring settings UI to allow more steps

- core/src/interactive.rs
- core/src/trick.rs
- frontend/src/Credits.tsx
- frontend/src/Initialize.tsx
- frontend/src/types.ts
> Support longest-throw-component-based throw evaluation policy

- core/src/trick.rs
- frontend/src/Credits.tsx
Fixes #251, probably also #252
> Fix TrickUnitLength throwevaluationpolicy for single tricks

- core/src/trick.rs
> Fix bug for one-tuple throws with longest tuple-based throw evaluation

- core/src/game_state.rs
- core/src/interactive.rs
- core/src/message.rs
- core/src/settings.rs
- frontend/src/Credits.tsx
- frontend/src/Initialize.tsx
- frontend/src/types.ts
> Add setting to avoid duplicate friends

- core/examples/simulate_play.rs
- core/src/game_state.rs
- core/src/scoring.rs
- frontend/shengji-wasm/src/lib.rs
- frontend/src/Credits.tsx
- frontend/src/Play.tsx
- frontend/src/Points.tsx
- frontend/src/WasmContext.tsx
- frontend/src/WasmProvider.tsx
Add a thing to check for the next threshold to end the game early if necessary
Fixes #277
> Allow games to be ended early

- backend/src/main.rs
- core/examples/simulate_play.rs
- core/src/game_state.rs
- core/src/interactive.rs
- core/src/message.rs
- frontend/src/Credits.tsx
- frontend/src/Play.tsx
- frontend/src/Points.tsx
- frontend/src/ProgressBar.tsx
- frontend/src/WasmContext.tsx
- frontend/src/types.ts
> Make the UI better when the game is ended early.

- core/src/game_state.rs
- core/src/settings.rs
- core/src/types.rs
- frontend/src/Credits.tsx
- frontend/src/Draw.tsx
- frontend/src/Errors.tsx
- frontend/src/Exchange.tsx
- frontend/src/Initialize.tsx
- frontend/src/KittySizeSelector.tsx
- frontend/src/Play.tsx
- frontend/src/types.ts
> Adds support for irregularly sized kitty

- core/src/deck.rs
- core/src/game_state.rs
- core/src/interactive.rs
- core/src/lib.rs
- core/src/message.rs
- core/src/scoring.rs
- core/src/settings.rs
- core/src/types.rs
- frontend/shengji-wasm/src/lib.rs
- frontend/src/Credits.tsx
- frontend/src/Initialize.tsx
- frontend/src/KittySizeSelector.tsx
- frontend/src/Play.tsx
- frontend/src/Points.tsx
- frontend/src/ProgressBar.tsx
- frontend/src/ScoringSettings.tsx
- frontend/src/WasmContext.tsx
- frontend/src/WasmProvider.tsx
- frontend/src/types.ts
> Implement per-deck configuration options

- Cargo.lock
- core/Cargo.toml
- core/src/ordered_card.rs
- core/src/scoring.rs
- core/src/trick.rs
- core/src/types.rs
- frontend/shengji-wasm/Cargo.toml
- frontend/shengji-wasm/src/lib.rs
Stack is limited on the frontend, and it's not clear that we're
benefiting much from the extra boilerplate and compile time.
> Switch to Vec rather than SmallVec

- core/examples/simulate_play.rs
- core/src/interactive.rs
- core/src/ordered_card.rs
- core/src/trick.rs
- frontend/shengji-wasm/src/lib.rs
- frontend/src/Credits.tsx
- frontend/src/Initialize.tsx
- frontend/src/types.ts
> Support protecting tractors from four of a kind

- core/src/game_state.rs
- core/src/interactive.rs
- core/src/settings.rs
- frontend/src/Credits.tsx
- frontend/src/FriendSelect.tsx
- frontend/src/Initialize.tsx
- frontend/src/types.ts
My friends and I play with the rule that any card be selected as a friend, including trumps. Do you mind if I make a change to allow this? 
And thanks so much for creating this! It's awesome!
> Finding friends: add option to allow selecting trumps as a friend

- frontend/src/Card.tsx
- frontend/src/Credits.tsx
- frontend/src/IconButton.tsx
- frontend/src/Root.tsx
- frontend/src/SettingsPane.tsx
- frontend/src/state/Settings.ts
- frontend/src/style.css
> Implement "dark mode" for shengji

- frontend/src/Credits.tsx
- frontend/src/Initialize.tsx
- frontend/src/ProgressBar.tsx
- frontend/src/RandomizePlayersButton.tsx
- frontend/src/Root.tsx
- frontend/src/style.css
- frontend/src/util/array.ts
> Add support for randomizing the player order

- core/src/bidding.rs
- core/src/interactive.rs
- core/src/types.rs
- frontend/src/Credits.tsx
- frontend/src/Initialize.tsx
for example, S2 S2 can be bid over H2 H2
> added functionality to bid with same number of cards but higher suit

- core/examples/simulate_play.rs
- core/src/game_state.rs
- core/src/interactive.rs
- core/src/message.rs
- core/src/settings.rs
- core/src/trick.rs
- frontend/shengji-wasm/src/lib.rs
- frontend/src/Credits.tsx
- frontend/src/Initialize.tsx
- frontend/src/Play.tsx
- frontend/src/WasmContext.tsx
- frontend/src/WasmProvider.tsx
- frontend/src/types.ts
> Support custom tractor requirements

- core/src/bidding.rs
- core/src/game_state.rs
- core/src/hands.rs
- core/src/interactive.rs
- core/src/message.rs
- core/src/ordered_card.rs
- core/src/player.rs
- core/src/settings.rs
- core/src/trick.rs
- core/src/types.rs
- frontend/shengji-wasm/src/lib.rs
- frontend/src/BidArea.tsx
- frontend/src/Credits.tsx
- frontend/src/Draw.tsx
- frontend/src/FriendSelect.tsx
- frontend/src/RankSelector.tsx
- frontend/src/Trump.tsx
- frontend/src/index.tsx
- frontend/src/types.ts
- frontend/src/websocketHandler.ts
- storage/tests/hash_map_storage_tests.rs
- storage/tests/redis_storage_tests.rs
Fixes #243. I didn't bother making it configurable yet. Also need to add changelog.
> Implement post-ace NT rank

- core/src/bidding.rs
- core/src/game_state.rs
- core/src/interactive.rs
- core/src/message.rs
- core/src/player.rs
- core/src/settings.rs
- core/src/types.rs
- frontend/src/Credits.tsx
- frontend/src/Draw.tsx
- frontend/src/Initialize.tsx
- frontend/src/RankSelector.tsx
- frontend/src/Root.tsx
- frontend/src/SettingsPane.tsx
- frontend/src/State.ts
- frontend/src/TitleHandler.tsx
- frontend/src/state/Settings.ts
- frontend/yarn.lock
Also add some features, like fixing #351.
Should hopefully resolve #243.
> Bugfixes for post-ace NT mode

- core/src/game_state.rs
- core/src/interactive.rs
- core/src/message.rs
- core/src/ordered_card.rs
- core/src/player.rs
- core/src/settings.rs
- frontend/src/Credits.tsx
- frontend/src/Initialize.tsx
- frontend/src/types.ts
- frontend/src/websocketHandler.ts
> Allow choice of final level

- backend/src/main.rs
- core/examples/simulate_play.rs
- core/src/game_state/draw_phase.rs
- core/src/game_state/exchange_phase.rs
- core/src/game_state/initialize_phase.rs
- core/src/game_state/mod.rs
- core/src/game_state/play_phase.rs
- core/src/hands.rs
- core/src/interactive.rs
- core/src/message.rs
- core/src/ordered_card.rs
- core/src/settings.rs
- core/src/trick.rs
Refactoring to clean up the codebase a little bit.
> Split game state into its individual structs

- core/src/bidding.rs
- core/src/message.rs
- frontend/src/Credits.tsx
- frontend/src/Initialize.tsx
- frontend/src/gen-types.d.ts
- frontend/src/gen-types.schema.json
> Support disabling joker bids

- frontend/src/Draw.tsx
- frontend/src/Root.tsx
- frontend/src/SettingsPane.tsx
- frontend/src/state/Settings.ts
- added to player settings 
- new dropdown in settings pane 
- added to interface & created a new localstorage setting 
- propagated to Draw component
> Enhancement: Add a setting for autodraw speed

- core/examples/simulate_play.rs
- core/src/ordered_card.rs
- core/src/trick.rs
- frontend/shengji-wasm/src/lib.rs
> Explore every possible match before concluding that a given throw should lose

- Cargo.lock
- backend/Cargo.toml
- backend/src/main.rs
- backend/src/serving_types.rs
- backend/src/shengji_handler.rs
- backend/src/state_dump.rs
- backend/src/utils.rs
- core/examples/simulate_play.rs
Mostly moving things around. Broke `main.rs` into multiple files; switched web framework from `warp` to `axum` for compile time and general popularity/support reasons.
> Refactor backend (warp->axum)

- core/examples/simulate_play.rs
- frontend/shengji-wasm/src/lib.rs
- mechanics/src/ordered_card.rs
- mechanics/src/trick.rs
This reverts commit 0bf2618c5d1e5ee9c3df6f26412760a53a3c02e4.
Temporary until #411 is resolved
> Revert "Explore every possible match before concluding that a given throw should fail (#402)"
