rbtying/shengji

README.md, frontend/src/Beeper.tsx, frontend/src/index.tsx
r? @rbtying 
Fixes #5
Updates beeper to be once every five seconds when it's your turn.
Tested by opening four tabs, starting a game:
- check and uncheck the beep checkbox when it's your turn
- start with checkbox checked, make it your turn
- after clicking a card, beeper stops
=> Add constant beeping noise on turn

frontend/src/AppStateProvider.tsx, frontend/src/Errors.tsx, frontend/src/Timeout.tsx, frontend/src/WebsocketProvider.tsx, frontend/src/index.tsx, frontend/src/localStorageState.ts, frontend/src/websocketHandler.ts
Moves all websocket-initiated state to AppState
- changed the behavior of errors -- instead of removing individual error messages, all disappear at the same time after 5000ms of no new errors
- Added WebsocketProvider, which does two things:
- Sets up connection to websocket, binds listeners to it, and updates AppState as needed
- Creates a `send` and allows users to read from it. Nobody does this yet; it's just set as a global
- Removed all ReactDOM.render except 1, put it into a bootstrap() function
=> Migrate state to application state

frontend/src/beep.ts
=> Use alert() when `AudioContext` is not defined

backend/src/main.rs, frontend/src/Beeper.tsx, frontend/src/Timeout.tsx, frontend/src/TimerProvider.tsx, frontend/src/index.tsx, frontend/static/timer-worker.js
This is mostly helpful for development: setTimeout / setInterval events
on tabs which are not in focus are constrained to fire at most once per
second, which makes the deal unbearably slow. However, WebWorkers are
not limited in this way, so we can use the worker's timer to implement
the frontend's timer.
This will probably make testing #8 easier.
=> Use a WebWorker for timers rather than the `window` ones

frontend/src/ChatMessage.tsx
r? @rbtying 
Use InlineCard in the bid log message.
Also fix a nil check on `variant.type`
I changed it to print multiple copies of the card, rather than a number in front because it looked weird when the numbers were the same:
=> Use InlineCard for bids

frontend/src/Chat.tsx
r? @rbtying 
We used to hold global variable to deal with mutable messages array. Now that it's immutable, we can rely on object equality to decide when to jump anchor. Also switched to use the `send` from hooks
=> Remove temp variable in Chat

core/src/game_state.rs, core/src/interactive.rs, core/src/message.rs, core/src/trick.rs, frontend/src/Credits.tsx, frontend/src/Initialize.tsx, frontend/src/Trump.tsx, frontend/src/types.ts
Fixes #56. As implemented, 6677 tractor will not draw out JJJ. This
makes the reasoning a little more consistent, though conflicts are
hopefully sufficiently infrequent to not care.
=> Add option to protect longer tuples from shorter tuples

core/src/game_state.rs, core/src/interactive.rs, core/src/message.rs, core/src/types.rs, frontend/src/AppStateProvider.tsx, frontend/src/GameStatisticsButton.tsx, frontend/src/GameStatisticsPane.tsx, frontend/src/Header.tsx, frontend/src/icons/BarChart.tsx, frontend/src/localStorageState.ts, frontend/src/state/GameStatistics.ts, frontend/src/websocketHandler.ts
Adds functionality to stores game statistics in local storage and adds a component to display statistics.
I added a `GameFinished` message that sends the relevant metadata to the frontend and then the `gameFinishedHandler` figures out what to do to manipulate local storage.
I kind of cargo culted what was going on with the `Settings` for the display part 😇
(edge case, no games yet)
=> Add statistics tracking across games in localstorage.

core/src/game_state.rs, core/src/trick.rs
Fixes #118 : the point at which we're willing to break longer tuples in protected-longer-tuple-mode is when all of the units are one card long, not when the next unit is one card long.
=> Fix decomposition case when protecting longer tuples

core/src/game_state.rs
Fixes #119 -- reverts an earlier change which allowed same-value "over" bidding, since "taking back" bids is now an option.
=> Only allow increasing bids

frontend/src/Credits.tsx, frontend/src/LabeledPlay.tsx
`null === null`, so this was making every LabeledPlay have the `next` class
=> only mark next if next is provided

frontend/src/WebsocketProvider.tsx
Fix race where the old callback and the new callback might interleave,
causing the healthcheck timer to unexpectedly fire. Preventing the timer
from firing is complex, especially since the setTimeout call is actually
running in a web worker, but we know that the healthcheck is only valid
if it's still the most recent timer, so we can resolve the user-facing
issue.
=> Fix race in healthcheck callback

core/src/trick.rs, frontend/src/Card.tsx, frontend/src/InlineCard.tsx, frontend/src/LabeledPlay.tsx, frontend/src/Trick.tsx, frontend/src/types.ts, frontend/src/util/array.ts, frontend/src/util/cardHelpers.ts, frontend/static/style.css, frontend/tsconfig.json
When a throw is made, show the individual components of the throw
separately -- except that the throw components which are single cards,
which should be grouped together.
Fixes #29
=> Show throw breakdowns in the UI

core/src/game_state.rs, frontend/src/Credits.tsx, frontend/src/Players.tsx, frontend/src/types.ts
Some people like to keep playing after the A rank. In theory, it would
probably be best to have an "NT" rank, but as an intermediary step,
let's allow players to keep track of an ephemeral "meta-level". Note:
there is no mechanism currently to _set_ the meta-level, though it
wouldn't be a big deal to add one.
Part of the prerequisites for #141
=> Add a "meta-level" concept and wrap ranks after A

core/src/game_state.rs, core/src/interactive.rs, core/src/message.rs, frontend/src/Credits.tsx, frontend/src/Initialize.tsx, frontend/src/types.ts
the request is landlord should have the exclusive privilege to start the game during play. (currently, the end game notification indicates the landlord will start the game, but anyone can). Some newly minted landlord feels HER hard earned victory was not sufficiently rewarded without the exclusive privilege to start a new game:)
=> restrict game start to the landlord unless no landlord is determined

frontend/shengji-wasm/src/lib.rs, frontend/src/Card.tsx, frontend/static/rules.html, frontend/static/style.css
Use Canvas text-bounding-box utilities to more accurately place the card character where it's supposed to be. Manually tested on Windows and MacOS default system fonts.
This will probably regress render performance a bit, but in exchange for allow the raise-on-hover functionality.
In order to not look weird on HiDPI screens, do the actual rendering via SVG tricks rather than canvas tricks. web tech is absurd
=> Tighten card boundaries using Canvas tricks

backend/src/main.rs, core/src/game_state.rs, core/src/interactive.rs, frontend/shengji-wasm/src/lib.rs, frontend/src/AppStateProvider.tsx, frontend/src/BidArea.tsx, frontend/src/Card.tsx, frontend/src/Cards.tsx, frontend/src/Draw.tsx, frontend/src/Exchange.tsx, frontend/src/Initialize.tsx, frontend/src/Play.tsx, frontend/src/Root.tsx, frontend/src/SettingsPane.tsx, frontend/src/WasmContext.tsx, frontend/src/WasmProvider.tsx, frontend/src/state/Settings.ts, frontend/src/style.css, frontend/src/types.ts, frontend/src/websocketHandler.ts
Rather than encoding cards twice (in a fairly expensive way!) on the
wire, use code in the frontend to generate the appropriate list-of-cards
format. Previously, we didn't do this because the sort order of the
cards was undefined without additional state; now, we can do better by
using logic in WASM to sort.
=> Use WASM to sort and group cards from the hands structure

core/src/trick.rs, frontend/src/Credits.tsx
Fix bug where throws of trump-rank-cards were blocked
The two-comparator problem bites again
=> Fix throw-check when throwing in trump

core/src/game_state.rs, core/src/interactive.rs, core/src/trick.rs, frontend/shengji-wasm/src/lib.rs, frontend/src/AutoPlayButton.tsx, frontend/src/Credits.tsx, frontend/src/Play.tsx, frontend/src/WasmContext.tsx, frontend/src/WasmProvider.tsx, frontend/src/types.ts
Part of the pathway to #197, fixes #142.
- Allow ambiguity-specification in backend and UI
- Tell you more information about what you're required to play (on
demand)
- Show you cards in the same suit on hover (setting)
- Separate cards by suit (setting)
=> Use WASM to implement a bunch of UI helpers

frontend/src/BidArea.tsx
turns out arrays and objects of number => object both use number as an
index.
Fixes #210
=> Fix bug where the incorrect trump number is highlighted

frontend/package.json, frontend/src/Card.tsx, frontend/src/Credits.tsx, frontend/src/InlineCard.tsx, frontend/src/SettingsPane.tsx, frontend/src/localStorageState.ts, frontend/src/state/Settings.ts, frontend/yarn.lock
Color-blind players may want to customize card colors to make the game
easier for them to play. Allow runtime configuration of colors on a
per-browser basis.
Mostly fixes #218
=> Support custom colors for non-SVG cards

core/src/game_state.rs, core/src/interactive.rs, core/src/message.rs, core/src/trick.rs, frontend/src/ChatMessage.tsx, frontend/src/Credits.tsx, frontend/src/Initialize.tsx, frontend/src/types.ts
Adds a setting on the initial page that allows users to toggle kitty reveal.
Message displayed when toggled
Message displayed at end of the game
Settings UI display
Great game by the way!
=> Support end of game kitty reveal

core/src/game_state.rs
Fixes #228
Note: I did not attempt to run this locally, so this code is untested.
=> Fix bug where kitty is not sent to chat if it contains no points

Cargo.lock, frontend/shengji-wasm/Cargo.toml, frontend/shengji-wasm/src/lib.rs, frontend/src/Credits.tsx, frontend/src/WebsocketProvider.tsx
1. re-use filereader on safari, otherwise filereader leaks memory
2. use the default allocator rather than wee_alloc, since wee_alloc doesn't
return any memory to the browser ever.
Fixes #233
=> Fix memory leak due to zstd compression

core/src/game_state.rs, core/src/interactive.rs, core/src/message.rs
to make it easier to see the points collected in chat board when end of game summary is dismissed too quickly
=> add game win, lost messages with points collected

Cargo.lock, core/Cargo.toml, core/examples/simulate_play.rs, core/src/lib.rs, core/src/ordered_card.rs, core/src/settings.rs, core/src/trick.rs, frontend/shengji-wasm/src/lib.rs, frontend/src/Credits.tsx
Re-implements trick-format decomposition as follows:
1. Support requirements on adjacent partial-tractors, e.g. XXXYY,
especially when decomposing longer tractors.
2. Generate a fixed ordering of required plays per number of cards in
the trick-unit, crossing both N-tuples and tractors. Generally treat
tractors as being composed of their base tuple
3. Memoize the computation of required plays because it's both fixed and
relatively expensive to compute
Notable changes:
- you're now required to play a tractor if the trick-format is 4-of-a-kind
(previously, this would never occur).
- triplets are now implicitly stronger than tractors (i.e. we'll draw a triplet
before a tractor); however, a triple on its own does *not* require a tractor
to be played (this seems reasonable, since otherwise you …
=> Reimplement trick-format decomposition

core/src/game_state.rs, core/src/interactive.rs, core/src/message.rs, core/src/settings.rs, core/src/trick.rs, frontend/src/Credits.tsx, frontend/src/Initialize.tsx, frontend/src/Play.tsx, frontend/src/types.ts
Add two requested features:
- setting to hide the player who beat the throw (fixes #266)
- setting to remove format-following constraint on plays (fixes #265)
=> Add setting to hide player who beat throw & setting to remove format-following constraint

core/src/game_state.rs, core/src/interactive.rs, core/src/settings.rs, frontend/src/Credits.tsx, frontend/src/FriendSelect.tsx, frontend/src/Initialize.tsx, frontend/src/types.ts
The group I play with plays with this rule, and I often forget about it when selecting friends.
By the way, thanks for building/maintaining this game!
=> Support a friend selection policy that disallows point cards

core/src/game_state.rs, frontend/src/Credits.tsx, frontend/src/FriendSelect.tsx, frontend/src/Initialize.tsx
I missed a subtle detail when implementing the `PointCardNotAllowed` policy in #269: `king` is supposed to be a valid friend selection when the landlord's rank is `ace`.
I assumed this an uncommonly rule, so I decided to amend the current rule instead of adding a new one. I'd be happy to make a separate one if people actually use the current version.
=> Update PointCardNotAllowed policy

frontend/src/Credits.tsx, frontend/src/Points.tsx, frontend/src/ProgressBar.tsx, frontend/src/style.css
Hi! I've loved playing Tractor on your website, thanks a lot for writing it! =) One addition I've always thought could be nice is to add a "progress bar" that keeps visual track of each team's points relative to the game's checkpoints. I've implemented it in this PR, but I'm a bit of a frontend noob, so please let me know what changes you'd like to see before approving!
- Tested locally with both Tractor and Finding Friends modes (screenshot below)
- Ran `yarn prettier --write` and `yarn lint --fix`
=> Add point progress bar visualization

Cargo.lock, frontend/shengji-wasm/Cargo.toml
Should allow the game to work on older browsers ("work") which don't support
mutable globals in wasm.
=> Update rust dependencies to pull in new wasm-bindgen

frontend/src/ProgressBar.tsx
In some situations (e.g., someone put a ton of points on the bottom),
the number of points allocated to a team can exceed the number of points
normally allowed in the game, which will in turn cause the points
progress bar to overflow the expected bounds.
Rendering a good UI here a bit annoying, but clamping the result to
0-100% at least means the UI won't break!
Disclaimer: I have not tested this code
=> ProgressBar: clamp percentage to 0-100%

frontend/src/AutoPlayButton.tsx, frontend/src/BeepButton.tsx, frontend/src/Card.tsx, frontend/src/Cards.tsx, frontend/src/Credits.tsx, frontend/src/Exchange.tsx, frontend/src/LabeledPlay.tsx, frontend/src/Play.tsx, frontend/src/SvgCard.tsx, frontend/src/Trick.tsx, frontend/src/style.css, frontend/static/rules.html
Due to incomplete migrations, the card styling was partly using font sizing (`8em`) and a carefully computed bound around the card glyph itself (`computeCardBound`). This is tricky on a per-OS basis because the default fonts on Windows and macOS and Linux render cards with very different bounding boxes. Not previously too much of an issue since the impact of the change is mostly to the upper bound of the card, but with the new card icons this becomes problematic.
=> Rework cards to entirely use computed sizes rather than font sizes in game

core/examples/simulate_play.rs, frontend/shengji-wasm/src/lib.rs, frontend/src/Credits.tsx, frontend/src/Play.tsx, frontend/src/gen-types.d.ts, frontend/src/gen-types.schema.json, mechanics/src/format_match.rs, mechanics/src/lib.rs, mechanics/src/multiset_iter.rs, mechanics/src/ordered_card.rs, mechanics/src/trick.rs
1. Implement a more efficient matching algorithm for finding possible plays
2. Only run the expensive computation for possible plays when requested (e.g. when the user accesses the help menu)
3. Add a button to suggest a valid following play (does not work if the user doesn't have enough cards in the appropriate suit)
Fixes #411
=> Performance optimizations for trick-format matching

backend/src/main.rs, backend/src/state_dump.rs, core/src/interactive.rs, core/src/message.rs, core/src/settings.rs, frontend/src/Credits.tsx, frontend/src/Initialize.tsx, frontend/src/JoinRoom.tsx, frontend/src/PublicRoomsPane.tsx, frontend/src/gen-types.d.ts, frontend/src/gen-types.schema.json, frontend/yarn.lock
First pass at: https://github.com/rbtying/shengji/issues/49
- Added a GameVisibility field. Defaults to `unlisted`, but can be toggled to `public`. In the future can be used for private games, etc.
- Added a PublicRoomsPane, with functionality to poll a new API that returns all public games and displays them on the first page. Is polled on first render, and then has a refresh button for ad hoc refreshes afterwards.
=> Implement Game Visibility And Add Public Rooms Panel on Front Page

Cargo.lock, backend/Cargo.toml, backend/build.rs, backend/src/main.rs, backend/src/shengji_handler.rs, core/Cargo.toml, core/examples/simulate_play.rs, frontend/json-schema-bin/Cargo.toml, frontend/shengji-wasm/Cargo.toml, frontend/shengji-wasm/src/lib.rs, mechanics/Cargo.toml, mechanics/src/ordered_card.rs, mechanics/src/trick.rs, storage/Cargo.toml
This fixes a bug that is a rare edge case.
Specifically: if the first player leads a trick-format of a 3x2 tractor, a 2x3 tractor, five-of-a-kind or larger, and a subsequent player does *not* have the ability to meet that trick format, the play they are forced to make instead is dictated by the decomposition of the trick format. That decomposition would, for example, start a 5-tuple, then go to a 4-tuple and a card, and then an adjacent triple-and-pair, and then a separate triple and pair. However, the play legality logic is actually order-dependent; the play requirement [3, 2] requires a triple followed by a pair, and the play requirement [2, 3] requires a pair followed by a triple. This meant that the decomposition skipped the [2, 3] case (and similar cases in larger numbers of cards), …
=> Fix bug where irregular adjacent tuples were not always forced to play

frontend/src/localStorageState.ts
`show_trick_in_player_order` doesn't get remembered properly on refresh because the default can override it. This tweaks how defaults are handled for loading booleans to respect "off" values.
=> Prevent boolean defaults from overriding saved values

core/src/game_state/draw_phase.rs, core/src/game_state/exchange_phase.rs, core/src/game_state/mod.rs, core/src/game_state/play_phase.rs, core/src/interactive.rs, core/src/message.rs, frontend/src/Credits.tsx, frontend/src/ResetButton.tsx, frontend/src/Root.tsx, frontend/src/gen-types.d.ts, frontend/src/gen-types.schema.json, frontend/src/style.css
Fixes #93 
Some notes:
- anyone is allowed to cancel the game resetting, not only the requestor
- there's a fair amount of duplicate code for handling the action, which already existed with the previous reset implementation. Happy to take a crack at refactoring that if you find it useful.
- thanks for making this game!
=> Require confirmation to reset game

mechanics/src/bidding.rs
Bug: Currently this bidding sequence at rank 2 is possible: 1x2D -> 2xLJ -> 2xHJ -> 2x2S -> 2xHJ -> 2x2H -> 2xHJ etc
Expected behaviour: Double of any suit should not be able to outbid double jokers
Actual behaviour: Double of any suit can outbid double jokers, so bidding can become an infinite loop
This is because in the fallback condition `new_bid.card.suit() > existing_bid.card.suit()`, jokers have a none value or something, so any suit is considered higher, so I added an additional condition before that.
Separately, currently this behaviour is enforced: `The new bid count must have a size of at least 2 in order to be compared by suit ranking`, so you can't have 1x2D -> 1x2S. I've never heard of this condition though, my gaming groups have always allowed that, and this behaviour is not …
=> Fix bug with double suits being able to outbid double joker

frontend/src/JoinRoom.tsx
If you hover over the `rules` hyperlink, it redirects to `https://robertying.com/shengji/rules`, which leads to a 404. Map it back to the actual page: `https://robertying.com/shengji/rules.html`.
=> Fix rules link

backend/src/shengji_handler.rs, core/src/message.rs, frontend/src/Credits.tsx, frontend/src/Initialize.tsx, frontend/src/gen-types.d.ts, frontend/src/gen-types.schema.json, mechanics/src/trick.rs
=> Adds option to protect both triples and tractors from pairs

frontend/json-schema-bin/src/main.rs, frontend/src/gen-types.d.ts, frontend/src/gen-types.schema.json
This PR modifies `json-schemabin/src/main.rs` so that the script attempts to `fs::copy` if the `fs::rename` fails. On my machine, this fails because I'm running Arch Linux and `/tmp` is mounted on a different device than `/home`.
You can see another example of this error in https://github.com/rust-lang/rustup/issues/1239.
Ideally, we would match on `e.kind()`, but unfortunately the `CrossesDevices` error enum value is not yet available in stable, only nightly (see https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html#variant.CrossesDevices).
Another simpler alternative here would be to _always_ do a `copy` instead of a `rename`, although this might slow down builds a little bit on unaffected machines.
=> fix: `yarn types` crash when /tmp is cross-device

frontend/webpack.config.js
This looked like a typo. Note that the import is `TerserJsPlugin`, not `TerserPlugin`.
=> fix: TerserJsPlugin in Webpack build was unused
